domain: benfradet.github.io
author: Ben Fradet
email: benjamin.fradet@gmail.com
title: Ben Fradet's blog

permalink: /blog/:year/:month/:day/:title
highlighter: pygments
timezone: FR
encoding: utf-8
markdown: kramdown
exclude:
    - README.md
    - scripts
