domain: benfradet.github.io
author: Ben Fradet
email: benjamin.fradet@gmail.com
title: Ben Fradet's blog

permalink: /blog/:year/:month/:day/:title
highlighter: rouge 
timezone: FR
encoding: utf-8
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
exclude:
    - README.md
    - scripts
